// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCZdL7CN4jvZcYVHumdrKDSVC3F7K_43wY',
    appId: '1:440811929836:web:1ef07fa9ad1b8c71a425c9',
    messagingSenderId: '440811929836',
    projectId: 'event-management-system-69a05',
    authDomain: 'event-management-system-69a05.firebaseapp.com',
    storageBucket: 'event-management-system-69a05.appspot.com',
    measurementId: 'G-2ZECBFSWET',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBj19nh-who6THmyGo2m6VhGi5D1RBAYdA',
    appId: '1:440811929836:android:be688f921ba43886a425c9',
    messagingSenderId: '440811929836',
    projectId: 'event-management-system-69a05',
    storageBucket: 'event-management-system-69a05.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBgq8rG7jXhzd7xvxWNYdrdecryjz9xrhs',
    appId: '1:440811929836:ios:9edf21cef429dc62a425c9',
    messagingSenderId: '440811929836',
    projectId: 'event-management-system-69a05',
    storageBucket: 'event-management-system-69a05.appspot.com',
    iosClientId:
        '440811929836-polaih29gvshs8cao0tqubfcpnkjmlne.apps.googleusercontent.com',
    iosBundleId: 'com.example.eventManagementSystem',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBgq8rG7jXhzd7xvxWNYdrdecryjz9xrhs',
    appId: '1:440811929836:ios:9edf21cef429dc62a425c9',
    messagingSenderId: '440811929836',
    projectId: 'event-management-system-69a05',
    storageBucket: 'event-management-system-69a05.appspot.com',
    iosClientId:
        '440811929836-polaih29gvshs8cao0tqubfcpnkjmlne.apps.googleusercontent.com',
    iosBundleId: 'com.example.eventManagementSystem',
  );
}
